update

diff --git a/froglet b/froglet
--- a/froglet
+++ b/froglet
@@ -1,61 +1,50 @@
 #!/bin/bash
 # Vorachet Jaroensawas 
 
-# Check gsl program
-if ! gsl -v  &> /dev/null
-then
-    printf "\ngsl program could not be found (installation guide https://github.com/imatix/gsl)\n"
-    exit
-fi
-
-if [ "$#" -eq  "0" ]
-then
-    printf "\nUse default config file ~/.froglet\n"
-    USER_CONFIG_FILE_PATH=~/.froglet
-    if [ -f "$USER_CONFIG_FILE_PATH" ]; then
-        printf "\nLoading ${USER_CONFIG_FILE_PATH}"
-    else 
-        printf "\n${USER_CONFIG_FILE_PATH} does not exist."
-        printf "\nFroglet usage:"
-        printf "\n(Use default config file at ~/.froglet)\n$ froglet\n"
-        printf "\n(Use user-defined config file)\n$ froglet <user_defined_config_file>\n"
-        printf "\n(Requried variables in the config file)"
-        printf "\nFROGLET_MODELS_FOLDER=/somwhere/mymodels"
-        printf "\nFROGLET_GENERATORS_FOLDER=/somwhere/mygenerators"
-        printf "\nFROGLET_OUTPUT_FOLDER=/somwhere/myoutput\n\n"
-        exit
-    fi
-else
-    printf "\nUse user-defined config file ${USER_CONFIG_FILE_PATH}\n"
-    USER_CONFIG_FILE_PATH=$1
-fi
-
-source ${USER_CONFIG_FILE_PATH}
-
-if [[ -z "${FROGLET_MODELS_FOLDER}" ]]; then
-    printf "\nFROGLET_MODELS_FOLDER is undefined in ${FROGLET_MODELS_FOLDER}\n"
-    exit
-fi
-
-if [[ -z "${FROGLET_GENERATORS_FOLDER}" ]]; then
-    printf "\nFROGLET_GENERATORS_FOLDER is undefined in ${FROGLET_GENERATORS_FOLDER}\n"
-    exit
-fi
-
-if [[ -z "${FROGLET_OUTPUT_FOLDER}" ]]; then
-    printf "\nFROGLET_OUTPUT_FOLDER is undefined in ${FROGLET_OUTPUT_FOLDER}\n"
-    exit
-fi
+FROGLET_MODELS_FOLDER=$(pwd)/models
+FROGLET_GENERATORS_FOLDER=$(pwd)/generators
+FROGLET_OUTPUT_FOLDER=$(pwd)/output
 
 printf "\n  FROGLET_MODELS_FOLDER = ${FROGLET_MODELS_FOLDER}"
 printf "\n  FROGLET_GENERATORS_FOLDER = ${FROGLET_GENERATORS_FOLDER}"
 printf "\n  FROGLET_OUTPUT_FOLDER = ${FROGLET_OUTPUT_FOLDER}\n"
+
+exitIfIGslProgramUninstalled() {
+    if ! gsl -v  &> /dev/null
+    then
+        echo ""
+        echo "gsl program could not be found (installation guide https://github.com/imatix/gsl)"
+        echo ""
+        exit
+    else
+        echo -e "\xE2\x9C\x94  Found GSL at $(which gsl)"
+    fi
+}
+exitIfIndexGeneratorUndefined() {
+    GENERATOR_INDEX_FILE=${FROGLET_GENERATORS_FOLDER}/index.gsl
+    if [ ! -f "${GENERATOR_INDEX_FILE}" ]; then
+        echo ""
+        echo "Cannot find Generator Index File"
+        echo "Expected file path = ${GENERATOR_INDEX_FILE}"
+        echo ""
+        exit
+    else
+        echo -e "\xE2\x9C\x94  Found Generator Index File at ${GENERATOR_INDEX_FILE}"
+    fi
+}
+
+echo ""
+
+exitIfIGslProgramUninstalled
+
+exitIfIndexGeneratorUndefined
 
 printf "\nChoose generator:\n"
 
 cd ${FROGLET_GENERATORS_FOLDER}
 select g in * ; do test -n "$g" && break; echo ">>> Invalid Selection"; done
 generator=$g
+
 
 cd ${FROGLET_MODELS_FOLDER}
 printf "\nChoose model:\n"
@@ -64,14 +53,25 @@ model=$m
 
 mkdir -p ${FROGLET_OUTPUT_FOLDER}
 
-printf "\nmodel = ${model}\n"
-printf "\ngenerator = ${generator}\n"
-printf "\noutput_folder ${FROGLET_OUTPUT_FOLDER}\n\n"
+clear 
 
-cd ${FROGLET_GENERATORS_FOLDER}/${generator}
+echo -e ""
+echo -e ""
+echo -e ""
+echo -e "\xE2\x9C\x94  Target Generator ${FROGLET_GENERATORS_FOLDER}/${generator}"
+echo -e "\xE2\x9C\x94  Target Model ${FROGLET_MODELS_FOLDER}/${model}"
+echo -e "\xE2\x9C\x94  Target Output Folder ${FROGLET_OUTPUT_FOLDER}"
 
-time gsl -a -p -script:index ${FROGLET_MODELS_FOLDER}/$model ${FROGLET_OUTPUT_FOLDER}
+cd ${FROGLET_GENERATORS_FOLDER}/
+echo -e ""
+echo -e ""
+echo -e "Generating..."
+echo -e ""
 
-printf "\nIf there is no error,\nthe generated files should be saved in ${FROGLET_OUTPUT_FOLDER}"
+model_without_extension=$(echo "$model" | cut -f 1 -d '.')
+gsl -a -p -q -script:index ${FROGLET_MODELS_FOLDER}/$model ${FROGLET_OUTPUT_FOLDER} ${model_without_extension}
 
-printf "\n\nEnjoy using Froglet! - https://github.com/vorachet/froglet \n\n"
+echo -e ""
+echo -e "\xE2\x9C\x94  Done"
+echo -e ""
+echo -e "Enjoy using Froglet! "
